CREATE TABLE `position_mapping_batches` (
  `id` VARCHAR(64) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'PREVIEW',
  `scope` JSON NULL,
  `totalCount` INTEGER NOT NULL DEFAULT 0,
  `matchedCount` INTEGER NOT NULL DEFAULT 0,
  `conflictCount` INTEGER NOT NULL DEFAULT 0,
  `appliedCount` INTEGER NOT NULL DEFAULT 0,
  `failedCount` INTEGER NOT NULL DEFAULT 0,
  `createdById` VARCHAR(64) NOT NULL,
  `createdByName` VARCHAR(100) NOT NULL,
  `confirmedById` VARCHAR(64) NULL,
  `confirmedByName` VARCHAR(100) NULL,
  `confirmedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `position_mapping_batches_status_createdAt_idx` (`status`, `createdAt`),
  INDEX `position_mapping_batches_createdById_createdAt_idx` (`createdById`, `createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `position_mapping_items` (
  `id` VARCHAR(64) NOT NULL,
  `batchId` VARCHAR(64) NOT NULL,
  `employeeId` VARCHAR(64) NOT NULL,
  `employeeName` VARCHAR(100) NOT NULL,
  `originalDepartmentId` VARCHAR(64) NULL,
  `originalDepartmentName` VARCHAR(100) NULL,
  `originalPositionName` VARCHAR(100) NULL,
  `employeeUpdatedAtSnapshot` DATETIME(3) NOT NULL,
  `suggestedPositionId` VARCHAR(64) NULL,
  `candidatePositionIds` JSON NOT NULL,
  `confirmedPositionId` VARCHAR(64) NULL,
  `matchStatus` VARCHAR(32) NOT NULL,
  `applyStatus` VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  `failureReason` VARCHAR(500) NULL,
  `appliedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `position_mapping_items_batchId_employeeId_key` (`batchId`, `employeeId`),
  INDEX `position_mapping_items_employeeId_createdAt_idx` (`employeeId`, `createdAt`),
  INDEX `position_mapping_items_matchStatus_applyStatus_idx` (`matchStatus`, `applyStatus`),
  CONSTRAINT `position_mapping_items_batchId_fkey` FOREIGN KEY (`batchId`) REFERENCES `position_mapping_batches`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `employee_position_histories` (
  `id` VARCHAR(64) NOT NULL,
  `employeeId` VARCHAR(64) NOT NULL,
  `employeeName` VARCHAR(100) NOT NULL,
  `changeType` VARCHAR(32) NOT NULL,
  `oldDepartmentId` VARCHAR(64) NULL,
  `oldDepartmentName` VARCHAR(100) NULL,
  `newDepartmentId` VARCHAR(64) NULL,
  `newDepartmentName` VARCHAR(100) NULL,
  `oldPositionId` VARCHAR(64) NULL,
  `oldPositionName` VARCHAR(100) NULL,
  `newPositionId` VARCHAR(64) NULL,
  `newPositionName` VARCHAR(100) NULL,
  `reason` VARCHAR(500) NULL,
  `source` VARCHAR(24) NOT NULL,
  `changedById` VARCHAR(64) NOT NULL,
  `changedByName` VARCHAR(100) NOT NULL,
  `changedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `idempotencyKey` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `employee_position_histories_idempotencyKey_key` (`idempotencyKey`),
  INDEX `employee_position_histories_employeeId_changedAt_idx` (`employeeId`, `changedAt`),
  INDEX `employee_position_histories_changeType_changedAt_idx` (`changeType`, `changedAt`),
  INDEX `employee_position_histories_changedById_changedAt_idx` (`changedById`, `changedAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
