CREATE TABLE `notifications` (
  `id` VARCHAR(64) NOT NULL,
  `eventType` VARCHAR(80) NOT NULL,
  `businessType` VARCHAR(40) NOT NULL,
  `businessId` VARCHAR(80) NOT NULL,
  `recipientId` VARCHAR(64) NOT NULL,
  `recipientName` VARCHAR(100) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NULL,
  `severity` ENUM('S0','S1','S2','S3') NOT NULL DEFAULT 'S2',
  `actionUrl` VARCHAR(500) NOT NULL,
  `requiresAck` BOOLEAN NOT NULL DEFAULT false,
  `dedupeKey` VARCHAR(191) NOT NULL,
  `metadata` JSON NULL,
  `readAt` DATETIME(3) NULL,
  `ackAt` DATETIME(3) NULL,
  `resolvedAt` DATETIME(3) NULL,
  `resolvedReason` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `notifications_dedupeKey_key` (`dedupeKey`),
  INDEX `notifications_recipientId_resolvedAt_createdAt_idx` (`recipientId`, `resolvedAt`, `createdAt`),
  INDEX `notifications_recipientId_readAt_createdAt_idx` (`recipientId`, `readAt`, `createdAt`),
  INDEX `notifications_businessType_businessId_resolvedAt_idx` (`businessType`, `businessId`, `resolvedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `notification_deliveries` (
  `id` VARCHAR(64) NOT NULL,
  `notificationId` VARCHAR(64) NOT NULL,
  `channel` ENUM('FEISHU') NOT NULL,
  `status` ENUM('PENDING','PROCESSING','SENT','FAILED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `nextAttemptAt` DATETIME(3) NULL,
  `sentAt` DATETIME(3) NULL,
  `lastError` VARCHAR(500) NULL,
  `leaseOwner` VARCHAR(100) NULL,
  `leaseExpiresAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `notification_deliveries_notificationId_channel_key` (`notificationId`, `channel`),
  INDEX `notification_deliveries_status_nextAttemptAt_idx` (`status`, `nextAttemptAt`),
  INDEX `notification_deliveries_leaseOwner_leaseExpiresAt_idx` (`leaseOwner`, `leaseExpiresAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `notification_deliveries_notificationId_fkey` FOREIGN KEY (`notificationId`) REFERENCES `notifications` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `reminder_schedules` (
  `id` VARCHAR(64) NOT NULL,
  `eventType` VARCHAR(80) NOT NULL,
  `businessType` VARCHAR(40) NOT NULL,
  `businessId` VARCHAR(80) NOT NULL,
  `recipientId` VARCHAR(64) NOT NULL,
  `recipientName` VARCHAR(100) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NULL,
  `severity` ENUM('S0','S1','S2','S3') NOT NULL DEFAULT 'S2',
  `actionUrl` VARCHAR(500) NOT NULL,
  `requiresAck` BOOLEAN NOT NULL DEFAULT false,
  `dedupeKey` VARCHAR(191) NOT NULL,
  `channels` JSON NOT NULL,
  `metadata` JSON NULL,
  `scheduledAt` DATETIME(3) NOT NULL,
  `escalationLevel` INTEGER NOT NULL DEFAULT 0,
  `status` ENUM('PENDING','PROCESSING','COMPLETED','CANCELED','FAILED') NOT NULL DEFAULT 'PENDING',
  `leaseOwner` VARCHAR(100) NULL,
  `leaseExpiresAt` DATETIME(3) NULL,
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `completedAt` DATETIME(3) NULL,
  `canceledAt` DATETIME(3) NULL,
  `cancelReason` VARCHAR(500) NULL,
  `lastError` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `reminder_schedules_dedupeKey_key` (`dedupeKey`),
  INDEX `reminder_schedules_status_scheduledAt_idx` (`status`, `scheduledAt`),
  INDEX `reminder_schedules_businessType_businessId_status_idx` (`businessType`, `businessId`, `status`),
  INDEX `reminder_schedules_leaseOwner_leaseExpiresAt_idx` (`leaseOwner`, `leaseExpiresAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `notification_rules` (
  `id` VARCHAR(64) NOT NULL,
  `eventType` VARCHAR(80) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `channels` JSON NOT NULL,
  `config` JSON NOT NULL,
  `updatedById` VARCHAR(64) NULL,
  `updatedByName` VARCHAR(100) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `notification_rules_eventType_key` (`eventType`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `user_channel_bindings` (
  `id` VARCHAR(64) NOT NULL,
  `userId` VARCHAR(64) NOT NULL,
  `channel` ENUM('FEISHU') NOT NULL,
  `externalUserId` VARCHAR(191) NOT NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `verifiedAt` DATETIME(3) NULL,
  `lastError` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `user_channel_bindings_userId_channel_key` (`userId`, `channel`),
  UNIQUE INDEX `user_channel_bindings_channel_externalUserId_key` (`channel`, `externalUserId`),
  INDEX `user_channel_bindings_active_channel_idx` (`active`, `channel`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
