import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const app = readFileSync(join(process.cwd(), 'src/App.tsx'), 'utf8');
const sidebar = readFileSync(join(process.cwd(), 'src/layouts/Sidebar.tsx'), 'utf8');
const page = readFileSync(join(process.cwd(), 'src/pages/Enablement/index.tsx'), 'utf8');
const home = readFileSync(join(process.cwd(), 'src/pages/Enablement/EnablementHome.tsx'), 'utf8');
const todayActionData = readFileSync(join(process.cwd(), 'src/pages/Enablement/todayActionData.ts'), 'utf8');
const knowledge = readFileSync(join(process.cwd(), 'src/pages/Enablement/KnowledgeCenter.tsx'), 'utf8');
const publishing = readFileSync(join(process.cwd(), 'src/pages/Enablement/PublishingCenter.tsx'), 'utf8');
const store = readFileSync(join(process.cwd(), 'src/store/useEnablementStore.ts'), 'utf8');

assert.match(app, /ROUTES\.ENABLEMENT/);
assert.match(app, /PERMISSION_KEYS\.ENABLEMENT/);
assert.match(sidebar, /label:\s*'赋能中台'/);
assert.match(page, /企业知识/);
assert.match(page, /发布管理/);
assert.match(page, /value:\s*'home',\s*label:\s*'今日行动'/);
assert.match(page, /activeTab === 'home'/);
assert.match(home, /演示数据/);
assert.match(home, /继续今天的学习/);
assert.match(home, /7天上岗地图/);
assert.match(home, /今天的任务/);
assert.match(home, /AI导师/);
assert.match(home, /管理视角/);
assert.match(home, /onOpenKnowledge/);
assert.match(home, /useSearchParams/);
assert.match(home, /searchParams\.get\('view'\) === 'management' && canManage/);
assert.match(home, /setSearchParams\(\{ view: next \}\)/);
assert.doesNotMatch(home, /\[view,\s*setView\]/);
assert.match(todayActionData, /currentDay:\s*3/);
assert.doesNotMatch(`${home}\n${todayActionData}`, /fetch\(|backendRequest|localStorage|AppStorage|BusinessRecord/);
assert.match(knowledge, /搜索公司知识/);
assert.match(knowledge, /匹配分.*hit\.score/);
assert.match(knowledge, /enablementApi\.getKnowledge/);
assert.match(knowledge, /detail\.contentText/);
assert.match(knowledge, /sourceReference/);
assert.match(knowledge, /<Dialog/);
assert.match(publishing, /导入Markdown/);
assert.match(publishing, /提交审核/);
assert.match(publishing, /正式发布/);
assert.match(publishing, /上传新版本/);
assert.match(publishing, /item\.contentText/);
assert.match(publishing, /待发布 Markdown 源文预览/);
assert.match(publishing, /校验和：/);
assert.match(publishing, /公开来源：/);
assert.match(publishing, /version\.status === 'REJECTED'/);
assert.match(publishing, /version\.status === 'CURRENT'/);
assert.match(publishing, /来源说明 \/ WPS知识路径/);
assert.match(publishing, /currentQueue/);
assert.match(publishing, /不是有效的 Markdown 文件/);
const workflowCardIndex = publishing.indexOf('const WorkflowCard');
const publishingCenterIndex = publishing.indexOf('const PublishingCenter');
assert.ok(workflowCardIndex >= 0 && workflowCardIndex < publishingCenterIndex, 'WorkflowCard must remain at module scope');
assert.doesNotMatch(store, /localStorage|AppStorage|BusinessRecord/);
assert.doesNotMatch(`${knowledge}\n${publishing}`, /storageKey|sourcePath/);
