CREATE TABLE `okr_cycles` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `year` INTEGER NOT NULL,
  `quarter` INTEGER NOT NULL,
  `startAt` DATETIME(3) NOT NULL,
  `endAt` DATETIME(3) NOT NULL,
  `checkInWeekday` INTEGER NOT NULL DEFAULT 5,
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  `activatedAt` DATETIME(3) NULL,
  `closedAt` DATETIME(3) NULL,
  `createdById` VARCHAR(64) NOT NULL,
  `createdByName` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `okr_cycles_year_quarter_key`(`year`, `quarter`),
  INDEX `okr_cycles_status_startAt_idx`(`status`, `startAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_objectives` (
  `id` VARCHAR(64) NOT NULL,
  `cycleId` VARCHAR(64) NOT NULL,
  `scope` VARCHAR(24) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `parentObjectiveId` VARCHAR(64) NULL,
  `ownerId` VARCHAR(64) NOT NULL,
  `ownerName` VARCHAR(100) NOT NULL,
  `departmentId` VARCHAR(64) NULL,
  `departmentNameSnapshot` VARCHAR(100) NULL,
  `positionId` VARCHAR(64) NULL,
  `positionNameSnapshot` VARCHAR(100) NULL,
  `weight` DECIMAL(7,2) NOT NULL,
  `progress` DECIMAL(7,2) NOT NULL DEFAULT 0,
  `health` VARCHAR(24) NOT NULL DEFAULT 'ON_TRACK',
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  `publishedAt` DATETIME(3) NULL,
  `publishedById` VARCHAR(64) NULL,
  `publishedByName` VARCHAR(100) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdById` VARCHAR(64) NOT NULL,
  `createdByName` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `okr_objectives_cycleId_status_updatedAt_idx`(`cycleId`, `status`, `updatedAt`),
  INDEX `okr_objectives_ownerId_cycleId_idx`(`ownerId`, `cycleId`),
  INDEX `okr_objectives_departmentId_cycleId_idx`(`departmentId`, `cycleId`),
  INDEX `okr_objectives_parentObjectiveId_idx`(`parentObjectiveId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_objectives_cycleId_fkey` FOREIGN KEY (`cycleId`) REFERENCES `okr_cycles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `okr_objectives_parentObjectiveId_fkey` FOREIGN KEY (`parentObjectiveId`) REFERENCES `okr_objectives`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_key_results` (
  `id` VARCHAR(64) NOT NULL,
  `objectiveId` VARCHAR(64) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `ownerId` VARCHAR(64) NOT NULL,
  `ownerName` VARCHAR(100) NOT NULL,
  `departmentId` VARCHAR(64) NULL,
  `departmentNameSnapshot` VARCHAR(100) NULL,
  `positionId` VARCHAR(64) NULL,
  `positionNameSnapshot` VARCHAR(100) NULL,
  `type` VARCHAR(24) NOT NULL,
  `direction` VARCHAR(24) NOT NULL,
  `baselineValue` DECIMAL(18,4) NOT NULL,
  `targetValue` DECIMAL(18,4) NOT NULL,
  `currentValue` DECIMAL(18,4) NOT NULL,
  `unit` VARCHAR(40) NULL,
  `weight` DECIMAL(7,2) NOT NULL,
  `progress` DECIMAL(7,2) NOT NULL DEFAULT 0,
  `health` VARCHAR(24) NOT NULL DEFAULT 'ON_TRACK',
  `source` VARCHAR(24) NOT NULL DEFAULT 'MANUAL',
  `dueAt` DATETIME(3) NULL,
  `lastCheckInAt` DATETIME(3) NULL,
  `createdById` VARCHAR(64) NOT NULL,
  `createdByName` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `okr_key_results_objectiveId_updatedAt_idx`(`objectiveId`, `updatedAt`),
  INDEX `okr_key_results_ownerId_lastCheckInAt_idx`(`ownerId`, `lastCheckInAt`),
  INDEX `okr_key_results_health_dueAt_idx`(`health`, `dueAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_key_results_objectiveId_fkey` FOREIGN KEY (`objectiveId`) REFERENCES `okr_objectives`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_check_ins` (
  `id` VARCHAR(64) NOT NULL,
  `keyResultId` VARCHAR(64) NOT NULL,
  `actorId` VARCHAR(64) NOT NULL,
  `actorName` VARCHAR(100) NOT NULL,
  `previousValue` DECIMAL(18,4) NOT NULL,
  `currentValue` DECIMAL(18,4) NOT NULL,
  `progress` DECIMAL(7,2) NOT NULL,
  `confidence` INTEGER NULL,
  `health` VARCHAR(24) NOT NULL,
  `blocker` TEXT NULL,
  `nextAction` TEXT NULL,
  `evidence` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `okr_check_ins_keyResultId_createdAt_idx`(`keyResultId`, `createdAt`),
  INDEX `okr_check_ins_actorId_createdAt_idx`(`actorId`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_check_ins_keyResultId_fkey` FOREIGN KEY (`keyResultId`) REFERENCES `okr_key_results`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_reviews` (
  `id` VARCHAR(64) NOT NULL,
  `objectiveId` VARCHAR(64) NOT NULL,
  `reviewerId` VARCHAR(64) NOT NULL,
  `reviewerName` VARCHAR(100) NOT NULL,
  `reviewerType` VARCHAR(24) NOT NULL,
  `score` DECIMAL(5,4) NOT NULL,
  `summary` TEXT NOT NULL,
  `lessons` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `okr_reviews_objectiveId_reviewerId_reviewerType_key`(`objectiveId`, `reviewerId`, `reviewerType`),
  INDEX `okr_reviews_reviewerId_createdAt_idx`(`reviewerId`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_reviews_objectiveId_fkey` FOREIGN KEY (`objectiveId`) REFERENCES `okr_objectives`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_task_links` (
  `id` VARCHAR(64) NOT NULL,
  `keyResultId` VARCHAR(64) NOT NULL,
  `taskId` VARCHAR(64) NOT NULL,
  `taskTitle` VARCHAR(200) NOT NULL,
  `linkedById` VARCHAR(64) NOT NULL,
  `linkedByName` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `okr_task_links_keyResultId_taskId_key`(`keyResultId`, `taskId`),
  INDEX `okr_task_links_taskId_idx`(`taskId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_task_links_keyResultId_fkey` FOREIGN KEY (`keyResultId`) REFERENCES `okr_key_results`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `okr_task_links_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `employee_tasks`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_metric_bindings` (
  `id` VARCHAR(64) NOT NULL,
  `keyResultId` VARCHAR(64) NOT NULL,
  `metricCode` VARCHAR(64) NOT NULL,
  `metricVersion` INTEGER NOT NULL DEFAULT 1,
  `scopeType` VARCHAR(24) NOT NULL,
  `scopeId` VARCHAR(64) NULL,
  `createdById` VARCHAR(64) NOT NULL,
  `createdByName` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `okr_metric_bindings_keyResultId_key`(`keyResultId`),
  INDEX `okr_metric_bindings_metricCode_scopeType_scopeId_idx`(`metricCode`, `scopeType`, `scopeId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_metric_bindings_keyResultId_fkey` FOREIGN KEY (`keyResultId`) REFERENCES `okr_key_results`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_metric_snapshots` (
  `id` VARCHAR(64) NOT NULL,
  `bindingId` VARCHAR(64) NOT NULL,
  `value` DECIMAL(18,4) NOT NULL,
  `sourceCount` INTEGER NULL,
  `qualityStatus` VARCHAR(24) NOT NULL DEFAULT 'OK',
  `detail` JSON NULL,
  `rangeStartAt` DATETIME(3) NOT NULL,
  `rangeEndAt` DATETIME(3) NOT NULL,
  `measuredAt` DATETIME(3) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `okr_metric_snapshots_bindingId_measuredAt_idx`(`bindingId`, `measuredAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_metric_snapshots_bindingId_fkey` FOREIGN KEY (`bindingId`) REFERENCES `okr_metric_bindings`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `okr_events` (
  `id` VARCHAR(64) NOT NULL,
  `cycleId` VARCHAR(64) NOT NULL,
  `objectiveId` VARCHAR(64) NULL,
  `keyResultId` VARCHAR(64) NULL,
  `actorId` VARCHAR(64) NOT NULL,
  `actorName` VARCHAR(100) NOT NULL,
  `action` VARCHAR(64) NOT NULL,
  `fromState` VARCHAR(24) NULL,
  `toState` VARCHAR(24) NULL,
  `detail` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `okr_events_cycleId_createdAt_idx`(`cycleId`, `createdAt`),
  INDEX `okr_events_objectiveId_createdAt_idx`(`objectiveId`, `createdAt`),
  INDEX `okr_events_keyResultId_createdAt_idx`(`keyResultId`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `okr_events_cycleId_fkey` FOREIGN KEY (`cycleId`) REFERENCES `okr_cycles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `okr_events_objectiveId_fkey` FOREIGN KEY (`objectiveId`) REFERENCES `okr_objectives`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `okr_events_keyResultId_fkey` FOREIGN KEY (`keyResultId`) REFERENCES `okr_key_results`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
