CREATE TABLE `browser_lead_syncs` (
  `id` VARCHAR(64) NOT NULL,
  `platform` VARCHAR(40) NOT NULL,
  `shopKey` VARCHAR(120) NOT NULL,
  `platformOrderNo` VARCHAR(160) NOT NULL,
  `operatorId` VARCHAR(64) NOT NULL,
  `operatorName` VARCHAR(100) NOT NULL,
  `contactSource` VARCHAR(24) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  `leadId` VARCHAR(64) NULL,
  `leadName` VARCHAR(200) NULL,
  `assignedTo` VARCHAR(100) NULL,
  `assignedToId` VARCHAR(64) NULL,
  `intakeStatus` VARCHAR(40) NULL,
  `orderRemarkStatus` VARCHAR(24) NOT NULL DEFAULT 'NOT_ATTEMPTED',
  `orderRemarkError` VARCHAR(1000) NULL,
  `remarkOperatorId` VARCHAR(64) NULL,
  `remarkOperatorName` VARCHAR(100) NULL,
  `attemptCount` INTEGER NOT NULL DEFAULT 1,
  `lastError` VARCHAR(1000) NULL,
  `completedAt` DATETIME(3) NULL,
  `orderRemarkedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `browser_lead_syncs_platform_shopKey_platformOrderNo_key` (`platform`, `shopKey`, `platformOrderNo`),
  INDEX `browser_lead_syncs_operatorId_createdAt_idx` (`operatorId`, `createdAt`),
  INDEX `browser_lead_syncs_status_updatedAt_idx` (`status`, `updatedAt`),
  INDEX `browser_lead_syncs_leadId_idx` (`leadId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
