import type { AuthenticatedUser } from '../../src/types/auth';
import { STORAGE_KEYS } from '../../src/shared/utils/constants';
import { PERMISSION_KEYS, hasPermission } from '../../src/shared/utils/permissions';
import { canReadStorageKey, canWriteStorageKey, isAssetStorageKey } from './assetStorageAccess';

export type LegacyStorageOperation = 'read' | 'write' | 'runtime';

type LegacyStoragePolicy = {
  read: readonly string[];
  write: readonly string[];
  runtime: boolean;
};

const policies: Record<string, LegacyStoragePolicy> = {};
const COMMAND_ONLY_WRITE_KEYS = new Set<string>([
  STORAGE_KEYS.CUSTOMERS,
  STORAGE_KEYS.LEADS,
  STORAGE_KEYS.ORDERS,
  STORAGE_KEYS.ORDER_APPLICATIONS,
  STORAGE_KEYS.DELIVERIES,
  STORAGE_KEYS.TAGS,
  STORAGE_KEYS.TAG_GROUPS,
]);

function register(
  keys: readonly string[],
  read: readonly string[],
  write: readonly string[],
  runtime = true,
): void {
  keys.forEach((key) => {
    policies[key] = { read, write, runtime };
  });
}

register([STORAGE_KEYS.LEADS], [PERMISSION_KEYS.LEADS_LIST],
  [PERMISSION_KEYS.LEADS_CREATE, PERMISSION_KEYS.LEADS_FOLLOW, PERMISSION_KEYS.LEADS_FLOW_CONFIG], false);
// Customer rows are record-query-only. Keep the key registered so legacy callers
// receive an explicit authorization failure instead of treating it as unknown.
register([STORAGE_KEYS.CUSTOMERS], [], [], false);
register([STORAGE_KEYS.ORDERS], [PERMISSION_KEYS.ORDER_MANAGE],
  [PERMISSION_KEYS.ORDER_CREATE, PERMISSION_KEYS.ORDER_EDIT, PERMISSION_KEYS.ORDER_DELETE], false);
register([STORAGE_KEYS.ORDER_APPLICATIONS], [PERMISSION_KEYS.ORDER_REVIEW_LIST],
  [PERMISSION_KEYS.ORDER_REVIEW], false);
register([STORAGE_KEYS.DELIVERIES], [PERMISSION_KEYS.DELIVERY_CENTER],
  [PERMISSION_KEYS.DELIVERY_MOVE_CARD, PERMISSION_KEYS.DELIVERY_STAGE_CONFIG]);
register([STORAGE_KEYS.COMMISSIONS],
  [PERMISSION_KEYS.FINANCE_MY_COMMISSION, PERMISSION_KEYS.FINANCE_SETTLEMENT, PERMISSION_KEYS.FINANCE_RECOVERY_SETTLEMENT, PERMISSION_KEYS.FINANCE_PAYOUT],
  [PERMISSION_KEYS.FINANCE_SETTLEMENT, PERMISSION_KEYS.FINANCE_RECOVERY_SETTLEMENT, PERMISSION_KEYS.FINANCE_PAYOUT]);
register([STORAGE_KEYS.COMMISSION_OPERATION_LOGS],
  [PERMISSION_KEYS.FINANCE_SETTLEMENT, PERMISSION_KEYS.FINANCE_RECOVERY_SETTLEMENT, PERMISSION_KEYS.FINANCE_PAYOUT],
  [PERMISSION_KEYS.FINANCE_SETTLEMENT, PERMISSION_KEYS.FINANCE_RECOVERY_SETTLEMENT, PERMISSION_KEYS.FINANCE_PAYOUT]);
register([STORAGE_KEYS.COMMISSION_SETTLEMENT_BATCHES],
  [PERMISSION_KEYS.FINANCE_PAYOUT, PERMISSION_KEYS.FINANCE_SETTLEMENT], [PERMISSION_KEYS.FINANCE_PAYOUT]);
register([
  STORAGE_KEYS.MONTHLY_COMMISSION_TIER_CONFIGS,
  STORAGE_KEYS.COMMISSION_RULES,
  STORAGE_KEYS.COMMISSION_ROLE_CONFIGS,
  STORAGE_KEYS.COMMISSION_PAYOUT_PLANS,
],
  [PERMISSION_KEYS.FINANCE_RULES], [PERMISSION_KEYS.FINANCE_RULES]);
register([STORAGE_KEYS.FINANCE],
  [PERMISSION_KEYS.FINANCE_OVERVIEW, PERMISSION_KEYS.FINANCE_FLOW, PERMISSION_KEYS.FINANCE_PAYOUT],
  [PERMISSION_KEYS.FINANCE_OVERVIEW, PERMISSION_KEYS.FINANCE_FLOW, PERMISSION_KEYS.FINANCE_PAYOUT]);
register([STORAGE_KEYS.RECOVERY_ORDERS], [PERMISSION_KEYS.AFTER_SALES_RECOVERY, PERMISSION_KEYS.AFTER_SALES_RECOVERY_REVIEW_LIST],
  [PERMISSION_KEYS.AFTER_SALES_RECOVERY_CREATE, PERMISSION_KEYS.AFTER_SALES_RECOVERY_EDIT, PERMISSION_KEYS.AFTER_SALES_RECOVERY_REVIEW, PERMISSION_KEYS.AFTER_SALES_RECOVERY_DELETE]);
register([STORAGE_KEYS.REFUNDS], [PERMISSION_KEYS.AFTER_SALES_REFUND, PERMISSION_KEYS.FINANCE_REFUND],
  [PERMISSION_KEYS.AFTER_SALES_REFUND, PERMISSION_KEYS.FINANCE_REFUND]);
register([STORAGE_KEYS.SERVICE_TICKETS], [PERMISSION_KEYS.AFTER_SALES_TICKETS], [PERMISSION_KEYS.AFTER_SALES_TICKETS]);
register([STORAGE_KEYS.OPPORTUNITIES], [PERMISSION_KEYS.CUSTOMER_VIEW_ORDERS], [PERMISSION_KEYS.CUSTOMER_CREATE_ORDER]);
register([STORAGE_KEYS.AI_CARDS], [PERMISSION_KEYS.CUSTOMER_AI_CARD], [PERMISSION_KEYS.CUSTOMER_AI_CARD]);
register([STORAGE_KEYS.AI_SESSIONS], [PERMISSION_KEYS.AI_CHAT], [PERMISSION_KEYS.AI_CHAT]);
register([STORAGE_KEYS.PRODUCTS, STORAGE_KEYS.PRODUCT_LEVELS], [PERMISSION_KEYS.SETTINGS_PRODUCTS], [PERMISSION_KEYS.SETTINGS_PRODUCTS]);
register(
  [STORAGE_KEYS.TAGS, STORAGE_KEYS.TAG_GROUPS],
  [PERMISSION_KEYS.CUSTOMER_LIST, PERMISSION_KEYS.LEADS_DETAIL],
  [PERMISSION_KEYS.SETTINGS_CUSTOMER_TAGS],
);
register([STORAGE_KEYS.USERS, STORAGE_KEYS.DEPARTMENTS, STORAGE_KEYS.POSITIONS],
  [PERMISSION_KEYS.SETTINGS_EMPLOYEES_DEPARTMENTS], [PERMISSION_KEYS.SETTINGS_EMPLOYEES_DEPARTMENTS]);
register([STORAGE_KEYS.ROLES], [PERMISSION_KEYS.SETTINGS_ROLES], [PERMISSION_KEYS.SETTINGS_ROLES]);
register([STORAGE_KEYS.ORGANIZATION_PROFILE, STORAGE_KEYS.ORGANIZATION_SCHEMA_VERSION],
  [PERMISSION_KEYS.SETTINGS_EMPLOYEES_DEPARTMENTS], [PERMISSION_KEYS.SETTINGS_EMPLOYEES_DEPARTMENTS]);
register([STORAGE_KEYS.ORDER_TYPE_CONFIGS], [PERMISSION_KEYS.SETTINGS_ORDER_TYPES], [PERMISSION_KEYS.SETTINGS_ORDER_TYPES]);
register([STORAGE_KEYS.CUSTOMER_LEVEL_CONFIGS], [PERMISSION_KEYS.SETTINGS_CUSTOMER_LEVELS], [PERMISSION_KEYS.SETTINGS_CUSTOMER_LEVELS]);
register([STORAGE_KEYS.LIFECYCLE_STATUS_CONFIGS], [PERMISSION_KEYS.SETTINGS_LIFECYCLE], [PERMISSION_KEYS.SETTINGS_LIFECYCLE]);
register([STORAGE_KEYS.LEAD_SOURCE_CONFIGS, STORAGE_KEYS.LEAD_FLOW_CONFIG, STORAGE_KEYS.LEAD_INTAKE_RECORDS],
  [PERMISSION_KEYS.SETTINGS_LEAD_FLOW, PERMISSION_KEYS.LEADS_INTAKE_STATUS],
  [PERMISSION_KEYS.SETTINGS_LEAD_FLOW, PERMISSION_KEYS.LEADS_FLOW_CONFIG]);
register([STORAGE_KEYS.AFTER_SALES_SOURCE_CONFIGS],
  [PERMISSION_KEYS.SETTINGS_AFTER_SALES_SOURCES, PERMISSION_KEYS.AFTER_SALES_RECOVERY_CREATE, PERMISSION_KEYS.AFTER_SALES_RECOVERY_EDIT],
  [PERMISSION_KEYS.SETTINGS_AFTER_SALES_SOURCES]);
register([STORAGE_KEYS.ECOMMERCE_SETTLEMENT_RECORDS],
  [PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_WORKBENCH, PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_HISTORY, PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_EXCEPTIONS, PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_TALENTS],
  [PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_WORKBENCH]);
register([STORAGE_KEYS.ECOMMERCE_SETTLEMENT_CONFIG],
  [PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_SETTINGS, PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_RULES],
  [PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_SETTINGS, PERMISSION_KEYS.ECOMMERCE_SETTLEMENT_RULES]);
register([STORAGE_KEYS.INITIALIZED], [PERMISSION_KEYS.HOME], [PERMISSION_KEYS.HOME]);

function hasAnyPermission(user: AuthenticatedUser, permissionKeys: readonly string[], action: 'read' | 'write'): boolean {
  return permissionKeys.some((permissionKey) => hasPermission(user, permissionKey, action));
}

export function isLegacyStorageKeyRegistered(key: string): boolean {
  return isAssetStorageKey(key) || Boolean(policies[key]);
}

export function canAccessLegacyStorageKey(
  user: AuthenticatedUser,
  key: string,
  operation: LegacyStorageOperation,
): boolean {
  if (isAssetStorageKey(key)) {
    return operation === 'write' ? canWriteStorageKey(user, key) : canReadStorageKey(user, key);
  }

  const policy = policies[key];
  if (!policy) return false;
  if (operation === 'runtime') return policy.runtime && hasAnyPermission(user, policy.read, 'read');
  if (operation === 'write' && COMMAND_ONLY_WRITE_KEYS.has(key)) return false;
  return operation === 'write'
    ? hasAnyPermission(user, policy.write, 'write')
    : hasAnyPermission(user, policy.read, 'read');
}
