CREATE TABLE `customer_todos` (
  `id` VARCHAR(64) NOT NULL,
  `customerId` VARCHAR(80) NOT NULL,
  `customerName` VARCHAR(200) NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` TEXT NULL,
  `status` ENUM('PENDING', 'COMPLETED', 'CANCELED') NOT NULL DEFAULT 'PENDING',
  `dueAt` DATETIME(3) NOT NULL,
  `executionMethod` VARCHAR(20) NOT NULL DEFAULT 'none',
  `assigneeId` VARCHAR(64) NOT NULL,
  `assigneeName` VARCHAR(100) NOT NULL,
  `createdById` VARCHAR(64) NOT NULL,
  `createdByName` VARCHAR(100) NOT NULL,
  `completedAt` DATETIME(3) NULL,
  `completedById` VARCHAR(64) NULL,
  `completedByName` VARCHAR(100) NULL,
  `canceledAt` DATETIME(3) NULL,
  `canceledById` VARCHAR(64) NULL,
  `canceledByName` VARCHAR(100) NULL,
  `cancelReason` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_todos_customerId_status_dueAt_idx` (`customerId`, `status`, `dueAt`),
  INDEX `customer_todos_assigneeId_status_dueAt_idx` (`assigneeId`, `status`, `dueAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
